---
title: "connecting_duckdb"
format: html
---

```{r}
library(tidyverse)
library(DBI)
library(duckdb)
```

Let's connect to our database

```{r}
conn <- DBI::dbConnect(duckdb::duckdb(), dbdir="bren-eds213-data/database/database.db")
```

Let's look at our tables

```{r}
DBI::dbListTables(conn)
```

```{r}
species <- tbl(conn, "Species")
```

## Let's do our first query

```{r}
species_a <- dbGetQuery(conn, "SELECT * FROM Species WHERE Code LIKE '%a'")
species_a
```

### There is a better way

```{r}
library(dbplyr)
```

```{r}
species %>%
    filter(Relevance=="Study species") %>% 
    select(Code, Scientific_name) %>%
    show_query()
```

```{r}
species_study <- species %>%
    filter(Relevance=="Study species") %>% 
    select(Code, Scientific_name) 
```

```{r}
class(species_study)

```

```{r}
species %>%
    group_by(Relevance) %>%
    summarize(num_species = n()) %>%
    show_query()
```

## You can also mutate

```{r}
species %>%
    mutate(Code_x = paste0("X", Code)) %>%
    show_query()
```

```{r}
species %>%
    mutate(Code_x = paste0("X", Code)) %>%
    collect()
```

## You can do joins!

```{r}
eggs_db <- tbl(conn, "Bird_eggs")
nests_db <- tbl(conn, "Bird_nests")
```

```{r}
nests_eggs_df <- left_join(nests_db, eggs_db, by="Nest_ID", keep = FALSE) %>%
    collect()
```

## Don't forget to close the database connection

```{r}
DBI::dbDisconnect(conn, shutdown=TRUE)
```